export const PageType = {
  HOME: 'HOME',
  PROJECT: 'PROJECT',
  PROJECT_LISTING: 'PROJECT_LISTING',
  CONTACT: 'CONTACT',
  PRINTING: 'PRINTING',
  ADMIN: 'ADMIN',
  ABOUT: 'ABOUT',
  DEPARTMENTS: 'DEPARTMENTS',
  PRIVACY: 'PRIVACY',
  TERMS: 'TERMS'
};
