export const ROUTES = {
  HOME: '/',
  PROJECTS: '/projects',
  PROJECT_DETAILS: '/project/:slug',
  PRINTING: '/printing',
  VIDEOS: '/videos',
  CONTACT: '/contact',
  ADMIN_PROJECTS: '/admin/projects',
  ADMIN_ADD_PROJECT: '/admin/projects/add',
  ADMIN_EDIT_PROJECT: '/admin/projects/edit/:slug',
  ADMIN_ENQUIRIES: '/admin/enquiries',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_ACCESS: '/admin-access',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_LOGIN: '/admin-login',
  LEARNING: '/learning',
  LEARNING_WORKSPACE: '/learning/workspace',
  LEARNING_FUNDAMENTALS: '/learning/fundamentals',
  LEARNING_COMPONENTS: '/learning/components',
  LEARNING_COMPONENT_DETAILS: '/learning/components/:slug'
};
