-- ========================================================================
-- FLYEN PLATFORM - SUPABASE STORAGE RLS POLICIES
-- ========================================================================
-- This script configures Row Level Security (RLS) policies for all Flyen
-- public and private storage buckets.
-- Execute this script inside your Supabase SQL Editor.
-- ========================================================================

-- Disable any existing conflicting policies on storage.objects to avoid collisions
-- (Supabase allows multiple policies, but clean names prevent duplication)
DROP POLICY IF EXISTS "Allow public read access on public buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated insert on public buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated update on public buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated delete on public buckets" ON storage.objects;

DROP POLICY IF EXISTS "Allow authenticated read access on private buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated insert on private buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated update on private buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated delete on private buckets" ON storage.objects;

-- ========================================================================
-- SECTION 1: PUBLIC BUCKETS POLICIES
-- Target Buckets: logos, favicons, profiles, website-assets, project-images, learning-images
-- ========================================================================

-- 1.1 SELECT: Anyone (anon and authenticated) can read public assets
CREATE POLICY "Allow public read access on public buckets" ON storage.objects
    FOR SELECT USING (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );

-- 1.2 INSERT: Only authenticated users (administrators) can upload public assets
CREATE POLICY "Allow authenticated insert on public buckets" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );

-- 1.3 UPDATE: Only authenticated users (administrators) can replace public assets
CREATE POLICY "Allow authenticated update on public buckets" ON storage.objects
    FOR UPDATE TO authenticated USING (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    ) WITH CHECK (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );

-- 1.4 DELETE: Only authenticated users (administrators) can delete public assets
CREATE POLICY "Allow authenticated delete on public buckets" ON storage.objects
    FOR DELETE TO authenticated USING (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );


-- ========================================================================
-- SECTION 2: PRIVATE BUCKETS POLICIES
-- Target Buckets: project-documents, project-videos, downloads, temporary
-- ========================================================================

-- 2.1 SELECT: Only authenticated users (administrators) can read private assets
-- (Anonymous users must download files using short-lived signed URLs generated by the server/client)
CREATE POLICY "Allow authenticated read access on private buckets" ON storage.objects
    FOR SELECT TO authenticated USING (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );

-- 2.2 INSERT: Only authenticated users (administrators) can upload private assets
CREATE POLICY "Allow authenticated insert on private buckets" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );

-- 2.3 UPDATE: Only authenticated users (administrators) can replace private assets
CREATE POLICY "Allow authenticated update on private buckets" ON storage.objects
    FOR UPDATE TO authenticated USING (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    ) WITH CHECK (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );

-- 2.4 DELETE: Only authenticated users (administrators) can delete private assets
CREATE POLICY "Allow authenticated delete on private buckets" ON storage.objects
    FOR DELETE TO authenticated USING (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );
