-- ========================================================================
-- FLYEN PLATFORM - MIGRATION 003: SUPABASE STORAGE RLS POLICIES
-- ========================================================================
-- TODO: 
-- Restrict upload/update/delete permissions to administrators
-- after introducing role-based authentication.
-- Currently, these policies grant write access to all "authenticated" users.
-- ========================================================================

-- Disable any existing conflicting policies on storage.objects to avoid collisions
DROP POLICY IF EXISTS "Allow public read access on public buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated insert on public buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated update on public buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated delete on public buckets" ON storage.objects;

DROP POLICY IF EXISTS "Allow authenticated read access on private buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated insert on private buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated update on private buckets" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated delete on private buckets" ON storage.objects;

-- Disable any existing conflicting policies on storage.buckets
DROP POLICY IF EXISTS "Allow public read access on buckets" ON storage.buckets;
DROP POLICY IF EXISTS "Allow authenticated bucket management" ON storage.buckets;


-- ========================================================================
-- PART 1: POLICIES FOR storage.buckets
-- ========================================================================

-- 1.1 SELECT: Allow everyone to read bucket metadata
CREATE POLICY "Allow public read access on buckets" ON storage.buckets
    FOR SELECT USING (true);

-- 1.2 ALL: Allow authenticated users to manage buckets
CREATE POLICY "Allow authenticated bucket management" ON storage.buckets
    FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- ========================================================================
-- PART 2: POLICIES FOR storage.objects (PUBLIC BUCKETS)
-- Target Buckets: logos, favicons, profiles, website-assets, project-images, learning-images
-- ========================================================================

-- 2.1 SELECT: Anyone (anon and authenticated) can read public assets
CREATE POLICY "Allow public read access on public buckets" ON storage.objects
    FOR SELECT USING (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );

-- 2.2 INSERT: Only authenticated users (administrators) can upload public assets
CREATE POLICY "Allow authenticated insert on public buckets" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );

-- 2.3 UPDATE: Only authenticated users (administrators) can replace public assets
CREATE POLICY "Allow authenticated update on public buckets" ON storage.objects
    FOR UPDATE TO authenticated USING (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    ) WITH CHECK (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );

-- 2.4 DELETE: Only authenticated users (administrators) can delete public assets
CREATE POLICY "Allow authenticated delete on public buckets" ON storage.objects
    FOR DELETE TO authenticated USING (
        bucket_id IN ('logos', 'favicons', 'profiles', 'website-assets', 'project-images', 'learning-images')
    );


-- ========================================================================
-- PART 3: POLICIES FOR storage.objects (PRIVATE BUCKETS)
-- Target Buckets: project-documents, project-videos, downloads, temporary
-- ========================================================================

-- 3.1 SELECT: Only authenticated users (administrators) can read private assets
-- (Anonymous users must download files using short-lived signed URLs generated by the server/client)
CREATE POLICY "Allow authenticated read access on private buckets" ON storage.objects
    FOR SELECT TO authenticated USING (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );

-- 3.2 INSERT: Only authenticated users (administrators) can upload private assets
CREATE POLICY "Allow authenticated insert on private buckets" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );

-- 3.3 UPDATE: Only authenticated users (administrators) can replace private assets
CREATE POLICY "Allow authenticated update on private buckets" ON storage.objects
    FOR UPDATE TO authenticated USING (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    ) WITH CHECK (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );

-- 3.4 DELETE: Only authenticated users (administrators) can delete private assets
CREATE POLICY "Allow authenticated delete on private buckets" ON storage.objects
    FOR DELETE TO authenticated USING (
        bucket_id IN ('project-documents', 'project-videos', 'downloads', 'temporary')
    );
